### ISSUE TITLE
Tem como usar domínio .com.br

### ISSUE THREAD

**Issue by luisfernandomangia** [mlabssoftware/m-l-a-b-s.com#1]
Boa tarde.
Muito obrigado por divulgar o seu script para a comunidade.
Nas instruções, você diz que tem que usar um domínio .com. Seu script também aceita domínio .com.br?

**Comment by marcelo-asilva** [comment]
Oi Boa Tarde

A principio acreditávamos que seria só domínios .com, mais após vários testes percebemos que funciona com qualquer domínio. A questão de utilizar o .com é por ser uma URL mais curta facilitando a utilização.

Abraço.

**Comment by luisfernandomangia** [comment]
oi marcelo, eu testei aqui com um dominio da empresa onde trabalho. http://bblender.com.br/clientes/teste-gif-facebook por ser uma url grande que nem vc falou, só retorna um gif só. Nos seus testes aconteceu isso?

**Comment by luisfernandomangia** [comment]
consegui consertar. Ta 100% vlw por compartilhar o script
